name: Proof HTML

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  proof_html:
    name: Proof HTML
    uses: anishathalye/proof-html@v2.1.2
    with:
      directory: ./site
